#!/usr/bin/env bash

set -ex
set -o pipefail



# Setup the submodules
git submodule init

# For each submodule, npm install and npm run build
git submodule foreach 'npm install && npm run build'

git submodule status

if [ -f ".env" ]; then
    # Source the .env file if it exists and export the variables
    set -a
    source .env
    set +a
fi

for file in $(find src -type f ); do
    echo "Running $file"
	# if file contains .bun, run bun otherwise run tsx
	if [[ $file ==  *".bun"* ]]; then
		bun run "$file" &
	else
		npx --yes tsx "$file" &
	fi
	wait -n "$(jobs -p)" # Wait for any job to finish
done
